#ifndef ERROR_H_
#define ERROR_H_

namespace Cobra {
	namespace Errors {

		enum ERROR_MSG {
			EXPECTED_FUNCTION_NAME = 1,
			EXPECTED_LEFT_PARENTHESE,
			UNEXPECTED_CHARACTER,
			EXPECTED_LEFT_BRACE,
			EXPECTED_RIGHT_BRACE,
			FILE_IO,
			MAIN_NOT_FOUND,
			UNDEFINED,
			MAX_ARG_LIMIT,
			EXPRECTED_OBJECT_NAME,
			EXPECTED_EQUALS,
			MISSING_SEMI_COLON,
			EXPECTED_OPERATOR,
			FUNCTION_NOT_FOUND,
			ILLEGAL_STRING_CONCATENATION
		};

		const char* toString(int e);

	}
}

#endif // ERROR_H_
